import { db } from '../db';
import { Meeting } from '../mock-db';

interface CalendarEventPayload {
  summary: string;
  description: string;
  start: { dateTime: string; timeZone: string };
  end: { dateTime: string; timeZone: string };
  location?: string;
}

// -------------------------------------------------------------------------
// REFRESH GOOGLE TOKEN
// -------------------------------------------------------------------------
async function refreshGoogleToken(refreshToken: string): Promise<{ access_token: string; expires_in: number } | null> {
  try {
    const response = await fetch('https://oauth2.googleapis.com/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        client_id: process.env.GOOGLE_CLIENT_ID || '',
        client_secret: process.env.GOOGLE_CLIENT_SECRET || '',
        refresh_token: refreshToken,
        grant_type: 'refresh_token',
      }),
    });

    if (!response.ok) {
      throw new Error(`Token refresh failed: ${response.statusText}`);
    }

    return await response.json();
  } catch (error) {
    console.error('[CALENDAR ERROR] Refreshing Google token failed:', error);
    return null;
  }
}

// -------------------------------------------------------------------------
// GET VALID ACCESS TOKEN
// -------------------------------------------------------------------------
async function getValidToken(employeeId: string, provider: 'google'): Promise<string | null> {
  const integrations = await db.getCalendarIntegrations(employeeId);
  const integration = integrations.find(c => c.provider === provider);
  if (!integration) return null;

  const now = new Date();
  const expiresAt = new Date(integration.expires_at);

  // If token is still valid (with 5-minute buffer)
  if (expiresAt.getTime() - now.getTime() > 5 * 60 * 1000) {
    return integration.access_token;
  }

  // Token expired - refresh it
  if (!integration.refresh_token) return null;

  console.log(`[CALENDAR] Token expired for ${provider}, refreshing...`);
  const refreshData = await refreshGoogleToken(integration.refresh_token);

  if (refreshData) {
    const newExpiresAt = new Date(Date.now() + refreshData.expires_in * 1000).toISOString();
    await db.saveCalendarIntegration({
      employee_id: employeeId,
      provider,
      access_token: refreshData.access_token,
      refresh_token: integration.refresh_token, // retain old refresh token
      expires_at: newExpiresAt
    });
    return refreshData.access_token;
  }

  return null;
}

// -------------------------------------------------------------------------
// HELPER UTILITIES: LINK & ICS GENERATORS
// -------------------------------------------------------------------------
export function generateMeetingLink(platform: string = 'Google Meet'): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz';
  const randStr = (len: number) => Array.from({ length: len }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  const randNum = (len: number) => Array.from({ length: len }, () => Math.floor(Math.random() * 10)).join('');

  const plat = (platform || '').toLowerCase();
  if (plat.includes('teams')) {
    return `https://teams.microsoft.com/l/meetup-join/19:meeting_${randStr(16)}@thread.v2/0`;
  } else if (plat.includes('zoom')) {
    return `https://zoom.us/j/${randNum(10)}`;
  } else if (plat.includes('webex')) {
    return `https://qevn.webex.com/qevn/j.php?MTID=m${randStr(16)}`;
  } else if (plat.includes('phone') || plat.includes('person')) {
    return '';
  }
  // For Google Meet: return empty so it must be generated by Google's API to be a valid room
  return '';
}

export function formatDateTimeICS(dateStr: string, timeStr: string): string {
  // dateStr: "YYYY-MM-DD", timeStr: "HH:mm"
  const cleanDate = dateStr.replace(/-/g, '');
  const cleanTime = timeStr.replace(/:/g, '') + '00';
  return `${cleanDate}T${cleanTime}`;
}

export function generateICSContent(meeting: Meeting, organizerName: string = 'QEVN CRM', organizerEmail: string = 'hello@qevn.in'): string {
  const dtStart = formatDateTimeICS(meeting.meeting_date, meeting.meeting_start);
  const dtEnd = formatDateTimeICS(meeting.meeting_date, meeting.meeting_end);
  const dtStamp = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  const uid = `meet_${meeting.id}_${Date.now()}@qevn.in`;

  const attendeesList = (meeting.attendees || '')
    .split(',')
    .map(e => e.trim())
    .filter(Boolean);

  let attendeeLines = '';
  attendeesList.forEach(email => {
    attendeeLines += `ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=${email}:mailto:${email}\r\n`;
  });

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//QEVN CRM//Meeting Scheduler//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:REQUEST',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${dtStamp}`,
    `DTSTART;TZID=${meeting.timezone || 'UTC'}:${dtStart}`,
    `DTEND;TZID=${meeting.timezone || 'UTC'}:${dtEnd}`,
    `SUMMARY:${meeting.meeting_title}`,
    `DESCRIPTION:${(meeting.meeting_notes || 'Scheduled via QEVN CRM').replace(/\n/g, '\\n')}`,
    `LOCATION:${meeting.meeting_link || 'Online Video Call'}`,
    `ORGANIZER;CN=${organizerName}:mailto:${organizerEmail}`,
    attendeeLines.trim(),
    'STATUS:CONFIRMED',
    'SEQUENCE:0',
    'END:VEVENT',
    'END:VCALENDAR'
  ].filter(Boolean).join('\r\n');
}

export function generateGoogleCalendarAddUrl(meeting: Meeting): string {
  const dtStart = `${meeting.meeting_date.replace(/-/g, '')}T${meeting.meeting_start.replace(/:/g, '')}00`;
  const dtEnd = `${meeting.meeting_date.replace(/-/g, '')}T${meeting.meeting_end.replace(/:/g, '')}00`;

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: meeting.meeting_title,
    dates: `${dtStart}/${dtEnd}`,
    details: meeting.meeting_notes || 'Scheduled via QEVN CRM',
    location: meeting.meeting_link || '',
    ctz: meeting.timezone || 'Asia/Kolkata',
    add: meeting.attendees || ''
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

export function generateOutlookCalendarAddUrl(meeting: Meeting): string {
  const startISO = `${meeting.meeting_date}T${meeting.meeting_start}:00`;
  const endISO = `${meeting.meeting_date}T${meeting.meeting_end}:00`;

  const params = new URLSearchParams({
    path: '/calendar/action/compose',
    rru: 'addevent',
    subject: meeting.meeting_title,
    startdt: startISO,
    enddt: endISO,
    body: meeting.meeting_notes || 'Scheduled via QEVN CRM',
    location: meeting.meeting_link || '',
    to: meeting.attendees || ''
  });

  return `https://outlook.live.com/calendar/0/deeplink/compose?${params.toString()}`;
}

// -------------------------------------------------------------------------
// MAIN SYNC SERVICE
// -------------------------------------------------------------------------
export const calendarService = {
  async syncMeetingToCalendar(meeting: Meeting, employeeId: string): Promise<{ calendarEventId?: string; meetingLink?: string; need_reconnect?: boolean; error?: string }> {
    const integrations = await db.getCalendarIntegrations(employeeId);
    const integration = integrations.find(i => i.provider === 'google');
    
    // Check if Google integration exists
    if (!integration) {
      if ((meeting.platform || 'Google Meet') === 'Google Meet') {
        return { 
          need_reconnect: true, 
          error: 'Your Google Calendar is not connected. Please connect your Google account to generate valid Google Meet links.' 
        };
      }
      return { 
        calendarEventId: `mock_${meeting.id}_cal`, 
        meetingLink: meeting.meeting_link || generateMeetingLink(meeting.platform) 
      };
    }

    const token = await getValidToken(employeeId, 'google');
    if (!token) {
      if ((meeting.platform || 'Google Meet') === 'Google Meet') {
        return { 
          need_reconnect: true, 
          error: 'Your Google Calendar connection has expired. Please reconnect your Google account.' 
        };
      }
      return { 
        calendarEventId: `mock_${meeting.id}_cal`, 
        meetingLink: meeting.meeting_link || generateMeetingLink(meeting.platform) 
      };
    }

    const eventStart = `${meeting.meeting_date}T${meeting.meeting_start}:00`;
    const eventEnd = `${meeting.meeting_date}T${meeting.meeting_end}:00`;

    try {
      const attendeesList = meeting.attendees
        ? meeting.attendees.split(',').map(email => ({ email: email.trim() })).filter(e => e.email.length > 0)
        : [];

      const eventPayload: any = {
        summary: meeting.meeting_title,
        description: meeting.meeting_notes || 'Scheduled via QEVN CRM',
        start: { dateTime: eventStart, timeZone: meeting.timezone || 'UTC' },
        end: { dateTime: eventEnd, timeZone: meeting.timezone || 'UTC' },
        attendees: attendeesList,
        conferenceData: {
          createRequest: {
            requestId: `meet-${meeting.id}-${Date.now()}`,
            conferenceSolutionKey: {
              type: 'hangoutsMeet'
            }
          }
        }
      };

      if (meeting.meeting_link && !meeting.meeting_link.includes('meet.google.com')) {
        eventPayload.location = meeting.meeting_link;
      }

      const res = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1&sendUpdates=all', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(eventPayload),
      });

      if (res.ok) {
        const data = await res.json();
        console.log('[CALENDAR SYNC] Successfully created Google Calendar event with Meet link:', data.id, data.hangoutLink);
        const meetingLink = data.hangoutLink || (data.conferenceData?.entryPoints?.[0]?.uri) || meeting.meeting_link;
        return { calendarEventId: data.id, meetingLink };
      } else {
        const errorText = await res.text();
        console.error('[CALENDAR SYNC] Google Calendar API error:', errorText);
        if (res.status === 401 || res.status === 403) {
          return { need_reconnect: true, error: 'Google Calendar authentication failed. Please reconnect your Google account.' };
        }
      }
    } catch (err: any) {
      console.error('[CALENDAR SYNC] Failed syncing event to Google:', err);
    }

    return { 
      calendarEventId: `mock_${meeting.id}_gcal`, 
      meetingLink: meeting.meeting_link || generateMeetingLink(meeting.platform) 
    };
  },

  async updateMeetingInCalendar(meeting: Meeting, employeeId: string): Promise<boolean> {
    if (!meeting.calendar_event_id || meeting.calendar_event_id.startsWith('mock_')) {
      console.log(`[CALENDAR UPDATE] Mock calendar update for event: ${meeting.calendar_event_id}`);
      return true;
    }

    const token = await getValidToken(employeeId, 'google');
    if (!token) return false;

    const eventStart = `${meeting.meeting_date}T${meeting.meeting_start}:00`;
    const eventEnd = `${meeting.meeting_date}T${meeting.meeting_end}:00`;

    try {
      const attendeesList = meeting.attendees
        ? meeting.attendees.split(',').map(email => ({ email: email.trim() })).filter(e => e.email.length > 0)
        : [];

      const res = await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${meeting.calendar_event_id}?sendUpdates=all`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          summary: meeting.meeting_title,
          description: meeting.meeting_notes,
          start: { dateTime: eventStart, timeZone: meeting.timezone },
          end: { dateTime: eventEnd, timeZone: meeting.timezone },
          location: meeting.meeting_link,
          attendees: attendeesList
        }),
      });
      if (res.ok) return true;
    } catch (err) {
      console.error('[CALENDAR UPDATE] Error updating event:', err);
    }
    return false;
  },

  async deleteMeetingFromCalendar(meeting: Meeting, employeeId: string): Promise<boolean> {
    if (!meeting.calendar_event_id || meeting.calendar_event_id.startsWith('mock_')) {
      console.log(`[CALENDAR DELETE] Mock calendar delete for event: ${meeting.calendar_event_id}`);
      return true;
    }

    const token = await getValidToken(employeeId, 'google');
    if (!token) return false;

    try {
      const res = await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${meeting.calendar_event_id}?sendUpdates=all`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`,
        }
      });
      if (res.ok) return true;
    } catch (err) {
      console.error('[CALENDAR DELETE] Error deleting event:', err);
    }
    return false;
  }
};
